### ISSUE TITLE
Can't type in search

### ISSUE THREAD

**Issue by meisme-dev** [jmanc3/winbar#32] opened 2022-02-06 00:34 UTC
It won't let me type

**Comment by jmanc3** [comment] 2022-02-06 15:10
What's your window manager? (Openbox, GNOME, KDE, XFCE, Awesome, ect.)

What I imagine the problem is going to be is that you will be running a program that always takes the input focus when ever it can. (Probably something that lets you do user-defined shortcuts or similar functionality)

**Comment by meisme-dev** [comment] 2022-02-06 15:38
Turns out it works on Xorg but not Wayland

**Comment by jmanc3** [comment] 2022-02-08 01:16
Yeah, making winbar work with Xwayland's compatibility layer is out of scope.

> Applications using X11 will work fine in Wayland via the Xwayland compatibility layer, however there may be input issues or other bugs introduced. When possible, using an application in its native Wayland mode is preferred. 
The above is from: https://wiki.debian.org/Wayland

**Closed by jmanc3** 2022-02-08 01:16 UTC
