### ISSUE TITLE
Segmentation fault on Ubuntu 22.04

### ISSUE THREAD

**Issue by RUvlad1** [jmanc3/winbar#62] opened 2024-01-02 21:44 UTC
Same problem happens on Pop!_OS 22.04

If I should add any other info please let me know

**Comment by jmanc3** [comment] 2024-01-03 12:04
Should be fixed in: 08157bc.

Let me know.

(BTW, I noticed that scroll doesn't work on menus. That's because by default Ubuntu runs wayland and, therefore runs winbar under xwayland and that's not 'fixed' for at the moment.)

**Comment by gsantner** [comment] 2024-01-04 12:21
Also Ubuntu 22.04 here (lxqt DE), crashes still on master.

Built it with Debug instead of Release mode, but not much info beside _stack smashing detected_.

![grafik](https://github.com/jmanc3/winbar/assets/6735650/da9def3b-9132-4f33-82f0-e2f2d3cda612)

**Comment by jmanc3** [comment] 2024-01-04 23:18
@gsantner I wasn't able to reproduce on my VM. Just installed Ubuntu 22.04, updated all packages, and built winbar. Installed lxqt package and after loading in, running winbar in terminal just worked normally (although taskbar is invisible for some reason although menus work)

can you do 'bt' in gdb after you crash

**Comment by gsantner** [comment] 2024-01-06 18:02
@jmanc3  Sorry thought I attsached one with bt already, but saw that it was trace 😄 .

Seems like some icon resolving code goes infinite recursive (which I didn't find to happen/crash otherwhere so far). 
 
![grafik](https://github.com/jmanc3/winbar/assets/6735650/2e2982e9-37f8-4def-b0ce-d25ac2db1850)

**Comment by jmanc3** [comment] 2024-01-07 20:15
@gsantner possibly fixed in [4555b79](https://github.com/jmanc3/winbar/commit/4555b799907655a588f42b85c98827aecf8c275c)

**Comment by RUvlad1** [comment] 2024-01-08 11:38
> Should be fixed in: [08157bc](https://github.com/jmanc3/winbar/commit/08157bcaa99031c307d37f401f8f39c721f740fc).
> 
> Let me know.

forgot to reply, it's fixed!

**Comment by gsantner** [comment] 2024-01-08 17:59
@jmanc3 
It helped, at least partially. It shows the bar now for a few milliseconds and the crashes immediate again. Here is the stacktrace:

![Screenshot_20240108-185657](https://github.com/jmanc3/winbar/assets/6735650/f931f648-3053-41be-91c2-05f192d59f6d)

**Comment by jmanc3** [comment] 2024-01-09 23:05
@gsantner latest commit shouldn't crash anymore assuming it was some parsing bug [7bae65f](https://github.com/jmanc3/winbar/commit/7bae65f02b6dfa787270db44c572482e6488eeb2)

If you still crash, the output of:
```bash
route
```
and
```bash
ip route
```
would be helpful. Winbar uses which ever is available so if you don't have one of them, that's fine.

**Comment by gsantner** [comment] 2024-01-11 19:31
@jmanc3 
Thank you, it's not crashing anymore now!

Sorry for hijacking this issue a bit, at first sight it looked like similar reason. But well, the project gained a few bugfixes this way 😄

**Closed** 2024-01-12 07:41 UTC
