### ISSUE TITLE
Clock sometimes gets stuck

### ISSUE THREAD

**Issue by pushqrdx** [jmanc3/winbar#15] opened 2021-05-27 23:07 UTC
I can't figure out exactly what causes this issue but it happened twice for me already, the time gets stuck even though in the calendar widget it's correct

**Comment by jmanc3** [comment] 2021-11-26 05:59
I, also, never really figured out how to reproduce this bug, so I still don't know how to fix it, but, my best guess at to what is happening is that we use up all the file descriptors (the default max is [1024](https://docs.oracle.com/cd/E19476-01/821-0505/file-descriptor-requirements.html)) and then aren't allowed to open any more. In a coming commit, I reworked how animations use file descriptors and so this problem should take longer to hit (the clock rarely gets stuck for me anymore). I'll figure out something longer-term later.

**Comment by jmanc3** [comment] 2022-02-08 01:18
I was keeping this open until I figured out why animations sometimes got stuck, and I finally did. The problem was that we were sometimes closing the wrong timeout's.

**Closed by jmanc3** 2022-02-08 01:18 UTC
Labels: bug
